### ISSUE TITLE
DefaultValueContainer.cs is missing

### ISSUE THREAD

**Issue by YangFan789** [Ninputer/VBF#2]
In the current commit, DefaultValueContainer.cs which is in VBF.Compilers.Parsers is missing. Did you forget to include this file?

Commit SHA1 :f0f73558ca6dab0e0db63be10b5a3c32a07a6be3

**Comment by Ninputer** [comment]
Sorry I'll  fix it later today. Thank you very much for pointing out this error.

发自我的 iPhone

**Comment by Ninputer** [comment]
Fixed
