### ISSUE TITLE
Exception throws when running Unit Test

### ISSUE THREAD

**Issue by DannyBaobei** [Ninputer/VBF#3]
我对NUnit不是很熟, 最开始想用NUnit Test Adapter在Test Explorer 中运行Unit Test. 但是Test Cases没有显示出来.

然后使用NUnit Runner GUI 来打开Compiler.UnitTest.dll, 会抛出一个 System.IO.FileLoadException,截图如下:
![image](https://cloud.githubusercontent.com/assets/1484156/10749511/0e5eaebc-7ca6-11e5-886b-7cc78df3a162.png)

最后使用"nunit-console Compiler.UnitTest", 仍然抛出异常, 截图如下
![image](https://cloud.githubusercontent.com/assets/1484156/10749439/63d002d4-7ca5-11e5-8685-a39f525f8533.png)

**Comment by DannyBaobei** [comment]
补充一下,开发环境是Visual Studio 2012 update 5, NUnit 2.6.3, Win7 SP1

**Comment by Ninputer** [comment]
hi，VBF编译的dll默认是延迟签名的，所以不能被NUnit加载. 您可以到项目属性里面取消签名，或者把所签public key加到CLR验证排除列表当中，用sn    -Vr即可。

发自我的 iPhone

**Comment by DannyBaobei** [comment]
明白了, 谢谢

**Comment by DannyBaobei** [comment]
![image](https://cloud.githubusercontent.com/assets/1484156/10752796/7a7e072a-7cc7-11e5-9630-4bf92c01a210.png)
