### ISSUE TITLE
Consider throw exception for Scanner.Read()

### ISSUE THREAD

**Issue by ljsnogard** [Ninputer/VBF#4]
See occasions like below:
```
while(true)
{
    Lexeme lexeme = this.scanner_.Read();
    if (lexeme.TokenIndex == -1 || lexeme.IsEndOfStream) break;

    // uncomment below and comment above line would cause OutOfMemoryException
    // if (lexeme.TokenIndex == -1) break;
    result.Add(lexeme);
}
```
If a scanner continues reading after the end of lexeme stream, please consider explicitly throw an exception.
Or an OutOfMemoryException will be thrown and sometimes it's difficult to find the cause.

**Comment by Ninputer** [comment]
Thanks for your advice. The reason currently scanner keep providing EOS after the last token is that the parser can use them to perform error recovery. I'll consider this problem again if the out of memory exception affects a lot. I may like to add an option to the scanner class to open and close this behavior. What do you think about it?

**Comment by ljsnogard** [comment]
Option for the behaviour would be nice.
